[package]
name = "FileGuardAdmin"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
windows = { version = "0.52.0", features = ["Win32_Foundation", "Win32_Security", "Win32_Storage", "Win32_Storage_InstallableFileSystems"] }
libc = "0.2.151"
clap = "3.2.25"
colored = "2.1.0"